# Usamos una imagen base de Python
FROM python:3.10.11

# Establecer variables de entorno
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Instalar dependencias
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Crear un usuario no-root
RUN useradd -m myuser

# Cambiar al usuario no-root
USER myuser

# Establecer el directorio de trabajo en el contenedor
WORKDIR /home/myuser/app

# Copiar el archivo de requisitos y el app.py al contenedor
COPY requirements.txt app.py ./

# Instalar las dependencias del proyecto usando el usuario no-root
RUN pip install --user --upgrade pip && pip install --user -r requirements.txt

# Comando para ejecutar la aplicación
CMD ["python", "./app.py"]
