version: '3.8'

services:
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

  # batch_processor :
  #   image: ghcr.io/felix-orduz/misw4204-batch:latest
  #   environment:
  #     CELERY_BROKER_URL: redis://redis:6379/0
  #     CELERY_RESULT_BACKEND: redis://redis:6379/0
  #     DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/conversor
  #   depends_on:
  #     - redis

  worker :
    restart: always
    image: ghcr.io/felix-orduz/misw4204-worker:latest
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/conversor
      SAVE_PATH: /file_conversor/uploaded/
      CONVERT_PATH: /file_conversor/processed/
      GOOGLE_APPLICATION_CREDENTIALS: /opt/key.json
    depends_on:
      - redis
    volumes:
      - "/opt/convertidor_nfs/uploaded/:/file_conversor/uploaded/"
      - "/opt/convertidor_nfs/processed/:/file_conversor/processed/"
      - "/home/felix_orduz/key.json:/opt/key.json"
